version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
        POSTGRES_USER: jee
        POSTGRES_PASSWORD: jee
        POSTGRES_DB: orderentry
    ports:
      - "5432:5432"
    networks:
      - network

  domain-backend:
    image: jboss/wildfly:20.0.1.Final
    depends_on:
      - postgres
    environment:
      DEBUG: ""
      SKIP_DB_CONFIG: "true"
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./widfly20/conf/standalone.xml:/wildfly/standalone/configuration/standalone.xml
    networks:
      - network

  app-backend:
    image: jboss/wildfly:20.0.1.Final
    depends_on:
    - domain-backend
    environment:
      DEBUG: ""
      SKIP_DB_CONFIG: "true"
    ports:
      - "8081:8080"
      - "9991:9990"
    volumes:
      - ./widfly20_app/conf/standalone.xml:/wildfly/standalone/configuration/standalone.xml
    networks:
      - network

networks:
  network:
    driver: bridge
    ipam:
      driver: default

